// Generated by CoffeeScript 1.10.0
(function() {
  var btnGroupTemplate, btnTemplate, buttonGroupViewModel, buttonViewModel, ko;

  ko = require('knockout');

  btnTemplate = require('../tpl/button.html');

  btnGroupTemplate = require('../tpl/buttonGroup.html');

  buttonViewModel = (function() {
    function buttonViewModel(params, componentInfo) {
      this.data = ko.dataFor(componentInfo.element);
      this.click = params.click ? params.click.bind(this.data) : function() {};
      this.active = ko.observable(false);
      this.hover = ko.observable(false);
      this.disposes = [];
      this.disable = ko.pureComputed((function(_this) {
        return function() {
          return ko.unwrap(params.disable || false);
        };
      })(this));
      this.loading = ko.pureComputed((function(_this) {
        return function() {
          return ko.unwrap(params.loading || false);
        };
      })(this));
      this.href = ko.pureComputed((function(_this) {
        return function() {
          return ko.unwrap(params.href || 'javascript:;');
        };
      })(this));
      this.cls = ko.pureComputed((function(_this) {
        return function() {
          var cls, fluid, shape, size, type;
          type = ko.unwrap(params.type || null);
          cls = 'ko-button';
          if (type) {
            cls = cls + " ko-" + type;
          }
          if (componentInfo.templateNodes.length === 0) {
            cls = cls + " ko-icon-only";
          }
          if (_this.active()) {
            cls = cls + " ko-active";
          }
          if (_this.hover()) {
            cls = cls + " ko-hover";
          }
          shape = ko.unwrap(params.shape || null);
          if (shape) {
            cls = cls + " ko-" + shape;
          }
          fluid = ko.unwrap(params.fluid || null);
          if (fluid) {
            cls = cls + " ko-fluid";
          }
          size = ko.unwrap(params.size || null);
          if (size) {
            cls = cls + " ko-" + size;
          }
          if (_this.disable() === true) {
            cls = cls + " ko-disable";
          }
          return cls;
        };
      })(this));
      this.icon = ko.pureComputed((function(_this) {
        return function() {
          var icon;
          icon = ko.unwrap(params.icon || null);
          if (icon) {
            return "iconfont icon-" + icon;
          } else {
            return null;
          }
        };
      })(this));
      this.icon_text = ko.pureComputed((function(_this) {
        return function() {
          return ko.unwrap(params.iconText || null);
        };
      })(this));
      this.disposes = this.disposes.concat([this.cls]);
    }

    buttonViewModel.prototype.mouseDown = function() {
      return this.active(true);
    };

    buttonViewModel.prototype.mouseUp = function() {
      return this.active(false);
    };

    buttonViewModel.prototype.mouseOver = function() {
      return this.hover(true);
    };

    buttonViewModel.prototype.mouseOut = function() {
      return this.hover(false);
    };

    buttonViewModel.prototype.dispose = function() {
      return ko.utils.arrayForEach(this.disposes, function(obj) {
        return obj.dispose();
      });
    };

    return buttonViewModel;

  })();

  ko.components.register('ko-button', {
    viewModel: {
      createViewModel: function(params, componentInfo) {
        return new buttonViewModel(params, componentInfo);
      }
    },
    template: btnTemplate
  });

  buttonGroupViewModel = (function() {
    function buttonGroupViewModel(params, componentInfo1) {
      this.componentInfo = componentInfo1;
      this.data = ko.dataFor(this.componentInfo.element);
      this.cls = ko.pureComputed(function() {
        var cls, shape, size, vertical;
        cls = 'ko-button-group';
        shape = ko.unwrap(params.shape || null);
        if (shape) {
          cls = cls + " ko-" + shape;
        }
        size = ko.unwrap(params.size || null);
        if (size) {
          cls = cls + " ko-" + size;
        }
        vertical = ko.unwrap(params.vertical || false);
        if (vertical) {
          cls = cls + " ko-vertical";
        }
        return cls;
      });
    }

    return buttonGroupViewModel;

  })();

  ko.components.register('ko-button-group', {
    viewModel: {
      createViewModel: function(params, componentInfo) {
        return new buttonGroupViewModel(params, componentInfo);
      }
    },
    template: btnGroupTemplate
  });

}).call(this);

//# sourceMappingURL=button.js.map
